version: "3.8"

services:
  php:
    restart: always
    container_name: php_container
    build:
      context: .
      dockerfile: Dockerfile.php
      target: dev
    volumes:
      - ../symfony_app:/app
    ports:
      - 8000:8000
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/app/public"]

  db:
    restart: always
    container_name: db_container
    build:
      context: .
      dockerfile: Dockerfile.database
      target: dev
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:5.2.1-fpm
    container_name: phpmyadmin_container
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  
  # apache:
  #   image: httpd:alpine3.18
  #   restart: always
  #   container_name: apache_container
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.serve
  #   volumes:
  #     - ../symfony_app:/app
  #   ports:
  #     - 80:80
    

  # composer:
  #   image: composer:lts
  #   restart: always
  #   container_name: composer_container
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.composer
  #   volumes:
  #     - ./home/arthur_ubuntu/exercices/tp-dockerSymfony:/app

  # phpMyAdmin:
  #   image: phpmyadmin:apache
  #   restart: always
  #   container_name: myAdmin_container

networks:
  dev:

volumes:
  db-data: