FROM nginx:1.21 AS preprod

# Supprimez le fichier de configuration par défaut de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiez le fichier de configuration Nginx personnalisé
COPY nginx/nginx.conf /etc/nginx/conf.d/